apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: kafka-network-policy
  namespace: kafka
spec:
  podSelector:
    matchLabels:
      app: kafka
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: todo-app
    - namespaceSelector:
        matchLabels:
          name: dapr-system
    - podSelector:
        matchLabels:
          app: kafka
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: todo-app
    - namespaceSelector:
        matchLabels:
          name: dapr-system