apiVersion: v1
kind: ResourceQuota
metadata:
  name: dapr-system-resource-quota
  namespace: dapr-system
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
    persistentvolumeclaims: "2"