apiVersion: v1
kind: ResourceQuota
metadata:
  name: kafka-resource-quota
  namespace: kafka
spec:
  hard:
    requests.cpu: "3"
    requests.memory: 4Gi
    limits.cpu: "6"
    limits.memory: 8Gi
    persistentvolumeclaims: "10"