apiVersion: v1
kind: ResourceQuota
metadata:
  name: todo-app-resource-quota
  namespace: todo-app
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 2Gi
    limits.cpu: "4"
    limits.memory: 4Gi
    persistentvolumeclaims: "4"
    services.loadbalancers: "2"